@startuml SingletonPattern
package "Singleton Pattern"{
    ' Singleton.getInstance().....
    class Singleton {
        - static instance: Singleton
        - Singleton()
        + static getInstance(): Singleton
    }

    note right of Singleton::getInstance
    if (instance == null){
        instance = new Singleton()
    }else{
        return instance
    }
    end note
}
    


