@startuml


abstract class Abstraction {
    -Bridge bridge
    +Abstraction(Bridge bridge)
    +operation()
}


interface Bridge {
    +implementor()
}


class ConcreteImplementorA implements Bridge {
    +implementor() : void
}


class ConcreteImplementorB implements Bridge {
    +implementor() : void
}


class RefinedAbstraction extends Abstraction {
    +operation() : void
}



Abstraction --> Bridge

@enduml
